# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.4.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "prioritize-client"
VERSION = "1.4.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Prioritize API",
    author="Peter Haller",
    author_email="peter.haller@prioritize-iot.de",
    url="https://github.com/phaller222/prioritize-python-client",
    keywords=["OpenAPI", "OpenAPI-Generator", "Prioritize API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache License 2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked &#39;experimental&#39; in their schema and may still change within the 1.x line.
    """,  # noqa: E501
    package_data={"prioritize_client": ["py.typed"]},
)
