# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.5.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from prioritize_client.models.currency_total import CurrencyTotal
from prioritize_client.models.equipment_cost_line import EquipmentCostLine
from typing import Optional, Set
from typing_extensions import Self

class EquipmentCostReport(BaseModel):
    """
    EquipmentCostReport
    """ # noqa: E501
    task_id: Optional[StrictInt] = Field(default=None, alias="taskId")
    lines: Optional[List[EquipmentCostLine]] = None
    totals: Optional[List[CurrencyTotal]] = None
    rates_missing: Optional[StrictBool] = Field(default=None, alias="ratesMissing")
    __properties: ClassVar[List[str]] = ["taskId", "lines", "totals", "ratesMissing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EquipmentCostReport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lines (list)
        _items = []
        if self.lines:
            for _item_lines in self.lines:
                if _item_lines:
                    _items.append(_item_lines.to_dict())
            _dict['lines'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in totals (list)
        _items = []
        if self.totals:
            for _item_totals in self.totals:
                if _item_totals:
                    _items.append(_item_totals.to_dict())
            _dict['totals'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EquipmentCostReport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "taskId": obj.get("taskId"),
            "lines": [EquipmentCostLine.from_dict(_item) for _item in obj["lines"]] if obj.get("lines") is not None else None,
            "totals": [CurrencyTotal.from_dict(_item) for _item in obj["totals"]] if obj.get("totals") is not None else None,
            "ratesMissing": obj.get("ratesMissing")
        })
        return _obj


