# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.4.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from prioritize_client.models.project_goal_property_document import ProjectGoalPropertyDocument
from prioritize_client.models.project_goal_property_numeric import ProjectGoalPropertyNumeric
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GOALREQUESTPROPERTIESINNER_ONE_OF_SCHEMAS = ["ProjectGoalPropertyDocument", "ProjectGoalPropertyNumeric"]

class GoalRequestPropertiesInner(BaseModel):
    """
    GoalRequestPropertiesInner
    """
    # data type: ProjectGoalPropertyDocument
    oneof_schema_1_validator: Optional[ProjectGoalPropertyDocument] = None
    # data type: ProjectGoalPropertyNumeric
    oneof_schema_2_validator: Optional[ProjectGoalPropertyNumeric] = None
    actual_instance: Optional[Union[ProjectGoalPropertyDocument, ProjectGoalPropertyNumeric]] = None
    one_of_schemas: Set[str] = { "ProjectGoalPropertyDocument", "ProjectGoalPropertyNumeric" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GoalRequestPropertiesInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: ProjectGoalPropertyDocument
        if not isinstance(v, ProjectGoalPropertyDocument):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProjectGoalPropertyDocument`")
        else:
            match += 1
        # validate data type: ProjectGoalPropertyNumeric
        if not isinstance(v, ProjectGoalPropertyNumeric):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProjectGoalPropertyNumeric`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GoalRequestPropertiesInner with oneOf schemas: ProjectGoalPropertyDocument, ProjectGoalPropertyNumeric. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GoalRequestPropertiesInner with oneOf schemas: ProjectGoalPropertyDocument, ProjectGoalPropertyNumeric. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ProjectGoalPropertyDocument
        try:
            instance.actual_instance = ProjectGoalPropertyDocument.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ProjectGoalPropertyNumeric
        try:
            instance.actual_instance = ProjectGoalPropertyNumeric.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GoalRequestPropertiesInner with oneOf schemas: ProjectGoalPropertyDocument, ProjectGoalPropertyNumeric. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GoalRequestPropertiesInner with oneOf schemas: ProjectGoalPropertyDocument, ProjectGoalPropertyNumeric. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ProjectGoalPropertyDocument, ProjectGoalPropertyNumeric]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


