# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.5.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ResourceDTO(BaseModel):
    """
    ResourceDTO
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    stationary: Optional[StrictBool] = None
    remote: Optional[StrictBool] = None
    ip: Optional[StrictStr] = None
    port: Optional[StrictInt] = None
    busy: Optional[StrictBool] = None
    max_slots: Optional[StrictInt] = Field(default=None, alias="maxSlots")
    latitude: Optional[StrictStr] = None
    longitude: Optional[StrictStr] = None
    mqtt_resource: Optional[StrictBool] = Field(default=None, alias="mqttResource")
    mqtt_uuid: Optional[StrictStr] = Field(default=None, alias="mqttUUID")
    mqtt_data_send_topic: Optional[StrictStr] = Field(default=None, alias="mqttDataSendTopic")
    mqtt_data_receive_topic: Optional[StrictStr] = Field(default=None, alias="mqttDataReceiveTopic")
    mqtt_online: Optional[StrictBool] = Field(default=None, alias="mqttOnline")
    mqtt_last_ping: Optional[datetime] = Field(default=None, alias="mqttLastPing")
    agent: Optional[StrictBool] = None
    department_id: Optional[StrictInt] = Field(default=None, alias="departmentId")
    resource_group_id: Optional[StrictInt] = Field(default=None, alias="resourceGroupId")
    occupied_slots: Optional[StrictInt] = Field(default=None, alias="occupiedSlots")
    cost_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="costRate")
    cost_currency: Optional[StrictStr] = Field(default=None, alias="costCurrency")
    cost_rate_unit: Optional[StrictStr] = Field(default=None, alias="costRateUnit")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "stationary", "remote", "ip", "port", "busy", "maxSlots", "latitude", "longitude", "mqttResource", "mqttUUID", "mqttDataSendTopic", "mqttDataReceiveTopic", "mqttOnline", "mqttLastPing", "agent", "departmentId", "resourceGroupId", "occupiedSlots", "costRate", "costCurrency", "costRateUnit"]

    @field_validator('cost_rate_unit')
    def cost_rate_unit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['HOUR', 'DAY', 'USAGE']):
            raise ValueError("must be one of enum values ('HOUR', 'DAY', 'USAGE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "stationary": obj.get("stationary"),
            "remote": obj.get("remote"),
            "ip": obj.get("ip"),
            "port": obj.get("port"),
            "busy": obj.get("busy"),
            "maxSlots": obj.get("maxSlots"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "mqttResource": obj.get("mqttResource"),
            "mqttUUID": obj.get("mqttUUID"),
            "mqttDataSendTopic": obj.get("mqttDataSendTopic"),
            "mqttDataReceiveTopic": obj.get("mqttDataReceiveTopic"),
            "mqttOnline": obj.get("mqttOnline"),
            "mqttLastPing": obj.get("mqttLastPing"),
            "agent": obj.get("agent"),
            "departmentId": obj.get("departmentId"),
            "resourceGroupId": obj.get("resourceGroupId"),
            "occupiedSlots": obj.get("occupiedSlots"),
            "costRate": obj.get("costRate"),
            "costCurrency": obj.get("costCurrency"),
            "costRateUnit": obj.get("costRateUnit")
        })
        return _obj


