# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.5.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from prioritize_client.models.resource_dto import ResourceDTO
from prioritize_client.models.resource_value_dto import ResourceValueDTO
from prioritize_client.models.telemetry_rule_dto import TelemetryRuleDTO
from typing import Optional, Set
from typing_extensions import Self

class ResourceStatusDTO(BaseModel):
    """
    ResourceStatusDTO
    """ # noqa: E501
    resource: Optional[ResourceDTO] = None
    latest_values: Optional[List[ResourceValueDTO]] = Field(default=None, alias="latestValues")
    telemetry_rules: Optional[List[TelemetryRuleDTO]] = Field(default=None, alias="telemetryRules")
    __properties: ClassVar[List[str]] = ["resource", "latestValues", "telemetryRules"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceStatusDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resource
        if self.resource:
            _dict['resource'] = self.resource.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in latest_values (list)
        _items = []
        if self.latest_values:
            for _item_latest_values in self.latest_values:
                if _item_latest_values:
                    _items.append(_item_latest_values.to_dict())
            _dict['latestValues'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in telemetry_rules (list)
        _items = []
        if self.telemetry_rules:
            for _item_telemetry_rules in self.telemetry_rules:
                if _item_telemetry_rules:
                    _items.append(_item_telemetry_rules.to_dict())
            _dict['telemetryRules'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceStatusDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource": ResourceDTO.from_dict(obj["resource"]) if obj.get("resource") is not None else None,
            "latestValues": [ResourceValueDTO.from_dict(_item) for _item in obj["latestValues"]] if obj.get("latestValues") is not None else None,
            "telemetryRules": [TelemetryRuleDTO.from_dict(_item) for _item in obj["telemetryRules"]] if obj.get("telemetryRules") is not None else None
        })
        return _obj


