# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.4.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TaskDTO(BaseModel):
    """
    TaskDTO
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    priority: Optional[StrictInt] = None
    task_status: Optional[StrictStr] = Field(default=None, alias="taskStatus")
    assignee_id: Optional[StrictInt] = Field(default=None, alias="assigneeId")
    goal_id: Optional[StrictInt] = Field(default=None, alias="goalId")
    process_instance_id: Optional[StrictStr] = Field(default=None, alias="processInstanceId")
    tracking_for_me: Optional[StrictBool] = Field(default=None, alias="trackingForMe")
    running_count: Optional[StrictInt] = Field(default=None, alias="runningCount")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "priority", "taskStatus", "assigneeId", "goalId", "processInstanceId", "trackingForMe", "runningCount"]

    @field_validator('task_status')
    def task_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CREATED', 'ESTIMATED', 'OPEN', 'ASSIGNED', 'STARTED', 'STOPPED', 'FINISHED', 'CANCELLED', 'CLOSED']):
            raise ValueError("must be one of enum values ('CREATED', 'ESTIMATED', 'OPEN', 'ASSIGNED', 'STARTED', 'STOPPED', 'FINISHED', 'CANCELLED', 'CLOSED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "priority": obj.get("priority"),
            "taskStatus": obj.get("taskStatus"),
            "assigneeId": obj.get("assigneeId"),
            "goalId": obj.get("goalId"),
            "processInstanceId": obj.get("processInstanceId"),
            "trackingForMe": obj.get("trackingForMe"),
            "runningCount": obj.get("runningCount")
        })
        return _obj


