# coding: utf-8

"""
    Prioritize API

    REST API of Prioritize, a resource, project and IoT orchestration platform. All endpoints live under /api/v1. From 1.0.0 on this REST surface is the stable public contract (SemVer); the Vaadin admin GUI and its @Route URLs are an implementation detail and NOT part of that promise. A few areas are marked 'experimental' in their schema and may still change within the 1.x line.

    The version of the OpenAPI document: 1.4.0
    Contact: peter.haller@prioritize-iot.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TelemetryRuleRequest(BaseModel):
    """
    TelemetryRuleRequest
    """ # noqa: E501
    datapoint: Optional[StrictStr] = None
    operator: Optional[StrictStr] = None
    threshold: Optional[Union[StrictFloat, StrictInt]] = None
    threshold_high: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="thresholdHigh")
    hysteresis: Optional[Union[StrictFloat, StrictInt]] = None
    severity: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["datapoint", "operator", "threshold", "thresholdHigh", "hysteresis", "severity", "enabled"]

    @field_validator('operator')
    def operator_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GT', 'LT', 'RANGE']):
            raise ValueError("must be one of enum values ('GT', 'LT', 'RANGE')")
        return value

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INFO', 'WARNING', 'CRITICAL']):
            raise ValueError("must be one of enum values ('INFO', 'WARNING', 'CRITICAL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TelemetryRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TelemetryRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datapoint": obj.get("datapoint"),
            "operator": obj.get("operator"),
            "threshold": obj.get("threshold"),
            "thresholdHigh": obj.get("thresholdHigh"),
            "hysteresis": obj.get("hysteresis"),
            "severity": obj.get("severity"),
            "enabled": obj.get("enabled")
        })
        return _obj


